const global = require('./global.js');

/* GLOBAL */
window.NAME_LAUNCHER = global.NAME_LAUNCHER;
window.FIRST_WINDOW_RESIZABLE = global.FIRST_WINDOW_RESIZABLE;

/* URL */

window.URL_USERITIUM_INSCRIPTION = global.URL_USERITIUM_INSCRIPTION
window.URL_USERITIUM_MDP = global.URL_USERITIUM_MDP
