
/* LOGIQUE */

const IS_PROD = (process.env.NODE_ENV === 'prod' || process.env.ELECTRON_ENV === 'prod');


/* GLOBAL */

const NAME_LAUNCHER = "TyroServ Launcher"
const VERSION_LAUNCHER = "0.1.9";

const FIRST_WINDOW_WIDHT = 1318;
const FIRST_WINDOW_HEIGHT = 710;
const FIRST_WINDOW_RESIZABLE = false;

const ONGLET_WIDHT = 830;
const ONGLET_HEIGHT = 660;
const ONGLET_RESIZABLE = false;

const ONGLET_MOD_NAME = "Mods";
const ONGLET_SETTING_NAME = "Paramètre";
const ONGLET_VERSION_NAME = "Version";

const TIMEOUT_REQUEST = 4000; /* ms */
const DELAY_REQUEST = 1000; /* ms */

const DEFAULT_MIN_PLAYER = 0;
const DEFAULT_MAX_PLAYER = 1000;

const DISCORD_CLIENT_ID = "849915439844687893";


/* DIR & FILE */

const PROD_DIR_INSTANCE = "/.TyroServ/";
const DEV_DIR_INSTANCE = "/.TyroServBeta/";

const DIR_INSTANCE_LAUNCHER = (IS_PROD ? PROD_DIR_INSTANCE : DEV_DIR_INSTANCE) + "Launcher/";
const DIR_INSTANCE_FACTION = (IS_PROD ? PROD_DIR_INSTANCE : DEV_DIR_INSTANCE) + "TyroServ-Faction/";
const DIR_INSTANCE_MINIGAME = (IS_PROD ? PROD_DIR_INSTANCE : DEV_DIR_INSTANCE) + "TyroServ-MiniGame/";
const DIR_INSTANCE_VANILLA = (IS_PROD ? PROD_DIR_INSTANCE : DEV_DIR_INSTANCE) + "TyroServ-Vanilla/";

const DIR_INSTANCE_MOD = "/mods";

const FILE_CACHE = "Launcher_Cache.json";
const FILE_SETTINGS = "Launcher_Setting.json";
const FILE_MODS = "Launcher_Mods.json";

const FILE_USER_TYROSERV = "usercachetyroserv.json";
const FILE_USER_TYROSERV_A2F = "usercachetyroserva2f.json";

const FILE_LAUNCH_GAME = "Launch.jar";

/* URL */

const URL_INSTANCE_CLIENT = "http://tyrolium.fr/Download/TyroServS3/instance.zip";

const API_GET_INFO_LAUNCHER = "https://tyrolium.fr/Download/TyroServS3/launcher/index.php";

const PROD_IP_SERVER_MC = "mc.tyroserv.fr";
const PROD_PORT_SERVER_MC = "";
const DEV_IP_SERVER_MC = "vps212.tyrolium.fr";
const DEV_PORT_SERVER_MC = ":25566";

const PROD_IP_SERVER_PING = "vps212.tyrolium.fr";
const PROD_PROTCOLE_SERVER_PING = "https://";
const DEV_IP_SERVER_PING = "127.0.0.1/Tyrolium-Uptime-InServer";
const DEV_PROTCOLE_SERVER_PING = "http://";

const PROD_API_GET_TYROSERV = "api-minecraft.tyroserv.fr";
const PROD_API_GET_TYROSERV_PROTOCOLE = "https://";
const DEV_API_GET_TYROSERV = "api-minecraft.tyroserv.fr";
const DEV_API_GET_TYROSERV_PROTOCOLE = "https://";

const SCALE_USERITIUM_SKIN = "20";
const URL_USERITIUM_SKIN_HEAD = "https://useritium.fr/uploads/skin/headView.php?scale=" + SCALE_USERITIUM_SKIN;
const URL_OFFICIEL_SKIN_HEAD = "https://minotar.net/helm/";

const URL_USERITIUM_INSCRIPTION = "https://useritium.fr/connect.php";
const URL_USERITIUM_MDP = "https://useritium.fr/password.php?create=yes"
const URL_USERITIUM_PP = "https://useritium.fr/uploads/pp/";
const URL_GENERATE_PP = "https://tyrolium.fr/generate-pp/";

const API_USERITIUM_CONNEXION = "https://useritium.fr/api-externe/index.php?controller=TyroServ&task=connect";
const API_USERITIUM_TOKEN = "https://useritium.fr/api-externe/index.php?controller=TyroServ&task=connectToken";

const PROD_URL_TYROSERV_SITEWEB = "tyroserv.fr";
const PROD_PROTOCOLE_TYROSERV_SITEWEB = "https://";
const DEV_URL_TYROSERV_SITEWEB = "beta.tyroserv.fr";
const DEV_PROTOCOLE_TYROSERV_SITEWEB = "https://";

const URL_TYROSERV_SITEWEB_PLAYER = (IS_PROD ? PROD_PROTOCOLE_TYROSERV_SITEWEB + PROD_URL_TYROSERV_SITEWEB : DEV_PROTOCOLE_TYROSERV_SITEWEB + DEV_URL_TYROSERV_SITEWEB) + "/player/";
const URL_TYROSERV_SITEWEB_CGU = (IS_PROD ? PROD_PROTOCOLE_TYROSERV_SITEWEB + PROD_URL_TYROSERV_SITEWEB : DEV_PROTOCOLE_TYROSERV_SITEWEB + DEV_URL_TYROSERV_SITEWEB) + "/cgu";
const URL_TYROSERV_SITEWEB_CGV = (IS_PROD ? PROD_PROTOCOLE_TYROSERV_SITEWEB + PROD_URL_TYROSERV_SITEWEB : DEV_PROTOCOLE_TYROSERV_SITEWEB + DEV_URL_TYROSERV_SITEWEB) + "/cgv";
const URL_TYROSERV_SITEWEB_TERMS = (IS_PROD ? PROD_PROTOCOLE_TYROSERV_SITEWEB + PROD_URL_TYROSERV_SITEWEB : DEV_PROTOCOLE_TYROSERV_SITEWEB + DEV_URL_TYROSERV_SITEWEB) + "/terms";

const URL_TYROSERV_BOUTIQUE = "https://tyrolium.tebex.io";


/* REQUEST */

const GET_NB_PLAYER = "https://mcapi.xdefcon.com/server/" + (IS_PROD ? PROD_IP_SERVER_MC + PROD_PORT_SERVER_MC : DEV_IP_SERVER_MC + DEV_PORT_SERVER_MC) + "/full/json";


module.exports = {

    /* GLOBAL */
    IS_PROD: IS_PROD,

    NAME_LAUNCHER: NAME_LAUNCHER,
    VERSION_LAUNCHER: VERSION_LAUNCHER,

    TITLE_FIRST_WINDOW: NAME_LAUNCHER + " - " + VERSION_LAUNCHER,
    TITLE_ONGLET: NAME_LAUNCHER + " - ",

    FIRST_WINDOW_WIDHT: FIRST_WINDOW_WIDHT,
    FIRST_WINDOW_HEIGHT: FIRST_WINDOW_HEIGHT,
    FIRST_WINDOW_RESIZABLE: FIRST_WINDOW_RESIZABLE,

    ONGLET_WIDHT: ONGLET_WIDHT,
    ONGLET_HEIGHT: ONGLET_HEIGHT,
    ONGLET_RESIZABLE: ONGLET_RESIZABLE,

    ONGLET_MOD_NAME:ONGLET_MOD_NAME,
    ONGLET_SETTING_NAME:ONGLET_SETTING_NAME,
    ONGLET_VERSION_NAME:ONGLET_VERSION_NAME,

    TIMEOUT_REQUEST:TIMEOUT_REQUEST,
    DELAY_REQUEST:DELAY_REQUEST,

    DEFAULT_MIN_PLAYER:DEFAULT_MIN_PLAYER,
    DEFAULT_MAX_PLAYER:DEFAULT_MAX_PLAYER,

    DISCORD_CLIENT_ID: DISCORD_CLIENT_ID,

    /* DIR */
    DIR_INSTANCE: IS_PROD ? PROD_DIR_INSTANCE : DEV_DIR_INSTANCE,
    DIR_INSTANCE_LAUNCHER: DIR_INSTANCE_LAUNCHER,
    DIR_INSTANCE_FACTION: DIR_INSTANCE_FACTION,
    DIR_INSTANCE_MINIGAME: DIR_INSTANCE_MINIGAME,
    DIR_INSTANCE_VANILLA: DIR_INSTANCE_VANILLA,


    /* URL */
    IP_SERVER_MC: IS_PROD ? PROD_IP_SERVER_MC + PROD_PORT_SERVER_MC : DEV_IP_SERVER_MC + DEV_PORT_SERVER_MC,
    IP_SERVER_PING: IS_PROD ? PROD_PROTCOLE_SERVER_PING + PROD_IP_SERVER_PING : DEV_PROTCOLE_SERVER_PING + DEV_IP_SERVER_PING,
    API_GET_TYROSERV: IS_PROD ? PROD_API_GET_TYROSERV_PROTOCOLE + PROD_API_GET_TYROSERV : DEV_API_GET_TYROSERV_PROTOCOLE + DEV_API_GET_TYROSERV,

    URL_USERITIUM_SKIN_HEAD: URL_USERITIUM_SKIN_HEAD,
    URL_OFFICIEL_SKIN_HEAD: URL_OFFICIEL_SKIN_HEAD,

    URL_USERITIUM_INSCRIPTION: URL_USERITIUM_INSCRIPTION,
    URL_USERITIUM_MDP: URL_USERITIUM_MDP,
    URL_USERITIUM_PP: URL_USERITIUM_PP,
    URL_GENERATE_PP: URL_GENERATE_PP,

    API_USERITIUM_CONNEXION: API_USERITIUM_CONNEXION,
    API_USERITIUM_TOKEN: API_USERITIUM_TOKEN,

    URL_TYROSERV_SITEWEB: IS_PROD ? PROD_PROTOCOLE_TYROSERV_SITEWEB + PROD_URL_TYROSERV_SITEWEB : DEV_PROTOCOLE_TYROSERV_SITEWEB + DEV_URL_TYROSERV_SITEWEB,
    URL_TYROSERV_SITEWEB_PLAYER : URL_TYROSERV_SITEWEB_PLAYER,
    URL_TYROSERV_SITEWEB_CGU : URL_TYROSERV_SITEWEB_CGU,
    URL_TYROSERV_SITEWEB_CGV : URL_TYROSERV_SITEWEB_CGV,
    URL_TYROSERV_SITEWEB_TERMS : URL_TYROSERV_SITEWEB_TERMS,

    URL_TYROSERV_BOUTIQUE : URL_TYROSERV_BOUTIQUE,

    /* REQUEST */
    GET_NB_PLAYER: GET_NB_PLAYER,

};